### ISSUE TITLE
Blank components should always be marked as complete

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [adaptlearning/adapt-contrib-blank#45]
### Subject of the issue/enhancement/features
To avoid course completion prevention when blank components are used, they should be marked as complete upon postRender on the page

### Your environment
* FW 5.X
* Chrome
* All devices

### Steps to reproduce
Create a course with blank components and page level progress

### Expected behaviour
PLP should fill immediately on page load. Clicking PLP will show blank components individually have completed

### Actual behaviour
Course will never complete as Blank components do not get marked this way

**Comment by paulstevendev** [comment]
Surely the actual behaviour is the course will complete as the blank page completes. The only thing that I can see doesn't happen is the page level progress doesn't show the blank component as having completed but it makes no sense to include the blank component in the page level progress as the user cannot see the blank components. For our particular use to detect a page has opened we only require one NOT optional blank component at the top of the page.
